config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true,
	               length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name, presence: true,length: {in: 2..20}, uniqueness: true
  validates :introduction,length: { maximum: 50}

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
   if @book.save
     flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
   else
     render :edit
   end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def correct_user
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book, url: books_path, local:true do |f| %>
    <div class="form-group">
      <%= f.label :Title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :Opinion %><br>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
    <% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <% @book.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <%= f.label :Title %><br>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <%= f.label :Opinion %><br>
        <%= f.text_area :body %>
      </div>

      <div class="form-group">
        <%= f.submit 'Update Book' %>
      </div>

      <div>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>

    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>
    errors prohibited this book from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <div class="form-error">
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user), class: 'hoge' do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', book: @newbook, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user), class: 'hoge' do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1>
      <p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <script src="https://kit.fontawesome.com/07c664e9b7.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Users", users_path, class:"fas fa-users nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Books", books_path, class:"fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %>
                </li>
                <li>
                   <%= link_to "Sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Log in", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </body>
  </header>

  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <main>
    <%= yield %>
  </main>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <h2><%= @user.errors.count %>
          errors prohibited this book from being saved:</h2>
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
      <% end %>

      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %><br>
          <%= f.text_field :name %>
        </div>

        <div class="form-group">
           <%= f.label :Image %><br>
           <%= f.attachment_field :profile_image %>
        </div>

        <div class="form-group">
          <%= f.label :Introduction %><br>
          <%= f.text_area :introduction %>
        </div>

        <%= f.submit 'Update User', class: "btn btn-secondary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path, class: '' do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
              　<% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>